// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeSwGh_1FoJFax56b2cFAQgsIvL6j1eUA',
    appId: '1:412475880422:web:a08742d354ef1e90d09c27',
    messagingSenderId: '412475880422',
    projectId: 'pratik-s-portfolio',
    authDomain: 'pratik-s-portfolio.firebaseapp.com',
    storageBucket: 'pratik-s-portfolio.firebasestorage.app',
    measurementId: 'G-58L0WQ8F97',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeSwGh_1FoJFax56b2cFAQgsIvL6j1eUA',
    appId: '1:412475880422:web:dbf81d410ce32798d09c27',
    messagingSenderId: '412475880422',
    projectId: 'pratik-s-portfolio',
    authDomain: 'pratik-s-portfolio.firebaseapp.com',
    storageBucket: 'pratik-s-portfolio.firebasestorage.app',
    measurementId: 'G-541RJ3Y8WS',
  );
}
